;  ASM code generated by mikroVirtualMachine for PIC - V. 7.0.0.3
;  Date/Time: 19/07/2017 08:25:08
;  Info: http://www.mikroelektronika.co.yu


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$EF71	F001			GOTO	_main
$0008	$	_Delay_1us:
;Delays.c,13 :: 			void Delay_1us()
;Delays.c,15 :: 			Delay_us(1);
$0008	$0000	    			NOP
$000A	$0000	    			NOP
;Delays.c,16 :: 			}
$000C	$0012	    			RETURN
$000E	$	_Delay_5500us:
;Delays.c,49 :: 			void Delay_5500us()
;Delays.c,51 :: 			Delay_us(5500);
$000E	$0E0F	    			MOVLW	15
$0010	$6E0B	    			MOVWF	STACK_11, 0
$0012	$0EFF	    			MOVLW	255
$0014	$6E0A	    			MOVWF	STACK_10, 0
$0016	$2E0B	    			DECFSZ	STACK_11, F, 0
$0018	$D001	    			BRA	$+2
$001A	$D003	    			BRA	$+4
$001C	$2E0A	    			DECFSZ	STACK_10, F, 0
$001E	$D7FE	    			BRA	$-1
$0020	$D7FA	    			BRA	$-5
$0022	$0E3E	    			MOVLW	62
$0024	$6E0A	    			MOVWF	STACK_10, 0
$0026	$2E0A	    			DECFSZ	STACK_10, F, 0
$0028	$D7FE	    			BRA	$-1
$002A	$0000	    			NOP
;Delays.c,52 :: 			}
$002C	$0012	    			RETURN
$002E	$	_Delay_50us:
;Delays.c,31 :: 			void Delay_50us()
;Delays.c,33 :: 			Delay_us(50);
$002E	$0E21	    			MOVLW	33
$0030	$6E0A	    			MOVWF	STACK_10, 0
$0032	$2E0A	    			DECFSZ	STACK_10, F, 0
$0034	$D7FE	    			BRA	$-1
;Delays.c,34 :: 			}
$0036	$0012	    			RETURN
$0038	$	_Lcd8_Cmd:
$0038	$C015	FFE9			MOVFF	Lcd8bit_main_global_dataAddress, FSR0L
$003C	$C016	FFEA			MOVFF	Lcd8bit_main_global_dataAddress+1, FSR0H
$0040	$C017	FFE1			MOVFF	Lcd8bit_main_global_ctrlAddress, FSR1L
$0044	$C018	FFE2			MOVFF	Lcd8bit_main_global_ctrlAddress+1, FSR1H
$0048	$6AEF	    			CLRF	INDF0, 0
$004A	$5234	    			MOVF	FARG_Lcd8_Cmd+0, 1, 0
$004C	$E000	    			BZ	L_Lcd8_Cmd_0
$004E	$	L_Lcd8_Cmd_0:
$004E	$BE34	    			BTFSC	FARG_Lcd8_Cmd+0, 7, 0
$0050	$8EEF	    			BSF	INDF0, __LCD8_DB7, 0
$0052	$BC34	    			BTFSC	FARG_Lcd8_Cmd+0, 6, 0
$0054	$8CEF	    			BSF	INDF0, __LCD8_DB6, 0
$0056	$BA34	    			BTFSC	FARG_Lcd8_Cmd+0, 5, 0
$0058	$8AEF	    			BSF	INDF0, __LCD8_DB5, 0
$005A	$B834	    			BTFSC	FARG_Lcd8_Cmd+0, 4, 0
$005C	$88EF	    			BSF	INDF0, __LCD8_DB4, 0
$005E	$B634	    			BTFSC	FARG_Lcd8_Cmd+0, 3, 0
$0060	$86EF	    			BSF	INDF0, __LCD8_DB3, 0
$0062	$B434	    			BTFSC	FARG_Lcd8_Cmd+0, 2, 0
$0064	$84EF	    			BSF	INDF0, __LCD8_DB2, 0
$0066	$B234	    			BTFSC	FARG_Lcd8_Cmd+0, 1, 0
$0068	$82EF	    			BSF	INDF0, __LCD8_DB1, 0
$006A	$B034	    			BTFSC	FARG_Lcd8_Cmd+0, 0, 0
$006C	$80EF	    			BSF	INDF0, __LCD8_DB0, 0
$006E	$5019	    			MOVF	Lcd8bit_main_global_cmd, 0, 0
$0070	$0A01	    			XORLW	1
$0072	$E103	    			BNZ	L_Lcd8_Cmd_1
$0074	$94E7	    			BCF	INDF1, __LCD8_RS, 0
$0076	$EF3E	F000			GOTO	L_Lcd8_Cmd_2
$007A	$	L_Lcd8_Cmd_1:
$007A	$84E7	    			BSF	INDF1, __LCD8_RS, 0
$007C	$	L_Lcd8_Cmd_2:
$007C	$82E7	    			BSF	INDF1, __LCD8_ENABLE, 0
$007E	$EC04	F000			CALL	_Delay_1us
$0082	$92E7	    			BCF	INDF1, __LCD8_ENABLE, 0
$0084	$5019	    			MOVF	Lcd8bit_main_global_cmd, 0, 0
$0086	$0A01	    			XORLW	1
$0088	$E103	    			BNZ	L_Lcd8_Cmd_3
$008A	$EC07	F000			CALL	_Delay_5500us
$008E	$D002	    			BRA	L_Lcd8_Cmd_4
$0090	$	L_Lcd8_Cmd_3:
$0090	$EC17	F000			CALL	_Delay_50us
$0094	$	L_Lcd8_Cmd_4:
$0094	$0012	    			RETURN
$0096	$	_Div_16x16_U:
$0096	$0100	    			MOVLB	0
$0098	$6A08	    			CLRF	STACK_8, 0
$009A	$6A09	    			CLRF	STACK_9, 0
$009C	$0E10	    			MOVLW	16
$009E	$6E0C	    			MOVWF	STACK_12, 0
$00A0	$3401	    			RLCF	STACK_1, W, 0
$00A2	$3608	    			RLCF	STACK_8, F, 0
$00A4	$3609	    			RLCF	STACK_9, F, 0
$00A6	$5004	    			MOVF	STACK_4, W, 0
$00A8	$5E08	    			SUBWF	STACK_8, F, 0
$00AA	$5005	    			MOVF	STACK_5, W, 0
$00AC	$A0D8	    			BTFSS	STATUS, C, 0
$00AE	$3C05	    			INCFSZ	STACK_5, W, 0
$00B0	$5E09	    			SUBWF	STACK_9, F, 0
$00B2	$B0D8	    			BTFSC	STATUS, C, 0
$00B4	$EF63	F000			GOTO	$+8
$00B8	$5004	    			MOVF	STACK_4, W, 0
$00BA	$2608	    			ADDWF	STACK_8, F, 0
$00BC	$5005	    			MOVF	STACK_5, W, 0
$00BE	$B0D8	    			BTFSC	STATUS, C, 0
$00C0	$3C05	    			INCFSZ	STACK_5, W, 0
$00C2	$2609	    			ADDWF	STACK_9, F, 0
$00C4	$90D8	    			BCF	STATUS, C, 0
$00C6	$3600	    			RLCF	STACK_0, F, 0
$00C8	$3601	    			RLCF	STACK_1, F, 0
$00CA	$2E0C	    			DECFSZ	STACK_12, F, 0
$00CC	$EF50	F000			GOTO	$-21
$00D0	$0012	    			RETURN
$00D2	$	_LCD8_Out:
$00D2	$D00F	    			BRA	L_LCD8_Out_12
$00D4	$	L_LCD8_Out_14:
$00D4	$0E80	    			MOVLW	128
$00D6	$6E2F	    			MOVWF	FARG_LCD8_Out+0, 0
$00D8	$D019	    			BRA	L_LCD8_Out_13
$00DA	$	L_LCD8_Out_15:
$00DA	$0EC0	    			MOVLW	192
$00DC	$6E2F	    			MOVWF	FARG_LCD8_Out+0, 0
$00DE	$D016	    			BRA	L_LCD8_Out_13
$00E0	$	L_LCD8_Out_16:
$00E0	$0E94	    			MOVLW	148
$00E2	$6E2F	    			MOVWF	FARG_LCD8_Out+0, 0
$00E4	$D013	    			BRA	L_LCD8_Out_13
$00E6	$	L_LCD8_Out_17:
$00E6	$0ED4	    			MOVLW	212
$00E8	$6E2F	    			MOVWF	FARG_LCD8_Out+0, 0
$00EA	$D010	    			BRA	L_LCD8_Out_13
$00EC	$	L_LCD8_Out_18:
$00EC	$0E80	    			MOVLW	128
$00EE	$6E2F	    			MOVWF	FARG_LCD8_Out+0, 0
$00F0	$D00D	    			BRA	L_LCD8_Out_13
$00F2	$	L_LCD8_Out_12:
$00F2	$502F	    			MOVF	FARG_LCD8_Out+0, 0, 0
$00F4	$0A01	    			XORLW	1
$00F6	$E0EE	    			BZ	L_LCD8_Out_14
$00F8	$502F	    			MOVF	FARG_LCD8_Out+0, 0, 0
$00FA	$0A02	    			XORLW	2
$00FC	$E0EE	    			BZ	L_LCD8_Out_15
$00FE	$502F	    			MOVF	FARG_LCD8_Out+0, 0, 0
$0100	$0A03	    			XORLW	3
$0102	$E0EE	    			BZ	L_LCD8_Out_16
$0104	$502F	    			MOVF	FARG_LCD8_Out+0, 0, 0
$0106	$0A04	    			XORLW	4
$0108	$E0EE	    			BZ	L_LCD8_Out_17
$010A	$D7F0	    			BRA	L_LCD8_Out_18
$010C	$	L_LCD8_Out_13:
$010C	$0430	    			DECF	FARG_LCD8_Out+1, 0, 0
$010E	$6E00	    			MOVWF	STACK_0, 0
$0110	$502F	    			MOVF	FARG_LCD8_Out+0, 0, 0
$0112	$2600	    			ADDWF	STACK_0, 1, 0
$0114	$C000	F02F			MOVFF	STACK_0, FARG_LCD8_Out+0
$0118	$0E01	    			MOVLW	1
$011A	$6E19	    			MOVWF	Lcd8bit_main_global_cmd, 0
$011C	$C000	F034			MOVFF	STACK_0, FARG_Lcd8_Cmd+0
$0120	$EC1C	F000			CALL	_Lcd8_Cmd
$0124	$6A19	    			CLRF	Lcd8bit_main_global_cmd, 0
$0126	$6A33	    			CLRF	LCD8_Out_i_L0, 0
$0128	$	L_LCD8_Out_19:
$0128	$5033	    			MOVF	LCD8_Out_i_L0, 0, 0
$012A	$2431	    			ADDWF	FARG_LCD8_Out+2, 0, 0
$012C	$6EE9	    			MOVWF	FSR0L, 0
$012E	$0E00	    			MOVLW	0
$0130	$2032	    			ADDWFC	FARG_LCD8_Out+3, 0, 0
$0132	$6EEA	    			MOVWF	FSR0L+1, 0
$0134	$CFEE	F000			MOVFF	POSTINC0, STACK_0
$0138	$5200	    			MOVF	STACK_0, 1, 0
$013A	$E00C	    			BZ	L_LCD8_Out_20
$013C	$5033	    			MOVF	LCD8_Out_i_L0, 0, 0
$013E	$2431	    			ADDWF	FARG_LCD8_Out+2, 0, 0
$0140	$6EE9	    			MOVWF	FSR0L, 0
$0142	$0E00	    			MOVLW	0
$0144	$2032	    			ADDWFC	FARG_LCD8_Out+3, 0, 0
$0146	$6EEA	    			MOVWF	FSR0L+1, 0
$0148	$CFEE	F034			MOVFF	POSTINC0, FARG_Lcd8_Cmd+0
$014C	$EC1C	F000			CALL	_Lcd8_Cmd
$0150	$2A33	    			INCF	LCD8_Out_i_L0, 1, 0
$0152	$D7EA	    			BRA	L_LCD8_Out_19
$0154	$	L_LCD8_Out_20:
$0154	$0E01	    			MOVLW	1
$0156	$6E19	    			MOVWF	Lcd8bit_main_global_cmd, 0
$0158	$0012	    			RETURN
$015A	$	_WordToStr:
$015A	$C031	FFE9			MOVFF	FARG_WordToStr+2, FSR0L
$015E	$C032	FFEA			MOVFF	FARG_WordToStr+3, FSR0H
$0162	$0E20	    			MOVLW	32
$0164	$6EEE	    			MOVWF	POSTINC0, 0
$0166	$0E20	    			MOVLW	32
$0168	$6EEE	    			MOVWF	POSTINC0, 0
$016A	$0E20	    			MOVLW	32
$016C	$6EEE	    			MOVWF	POSTINC0, 0
$016E	$0E20	    			MOVLW	32
$0170	$6EEE	    			MOVWF	POSTINC0, 0
$0172	$0E20	    			MOVLW	32
$0174	$6EEE	    			MOVWF	POSTINC0, 0
$0176	$6AEF	    			CLRF	INDF0, 0
$0178	$0E01	    			MOVLW	1
$017A	$6E33	    			MOVWF	WordToStr_len_L0, 0
$017C	$0E00	    			MOVLW	0
$017E	$6E00	    			MOVWF	STACK_0, 0
$0180	$5030	    			MOVF	FARG_WordToStr+1, 0, 0
$0182	$5C00	    			SUBWF	STACK_0, 0, 0
$0184	$E102	    			BNZ	L_WordToStr_55
$0186	$502F	    			MOVF	FARG_WordToStr+0, 0, 0
$0188	$0809	    			SUBLW	9
$018A	$	L_WordToStr_55:
$018A	$A0D8	    			BTFSS	STATUS, C, 0
$018C	$2A33	    			INCF	WordToStr_len_L0, 1, 0
$018E	$	L_WordToStr_4:
$018E	$0E00	    			MOVLW	0
$0190	$6E00	    			MOVWF	STACK_0, 0
$0192	$5030	    			MOVF	FARG_WordToStr+1, 0, 0
$0194	$5C00	    			SUBWF	STACK_0, 0, 0
$0196	$E102	    			BNZ	L_WordToStr_56
$0198	$502F	    			MOVF	FARG_WordToStr+0, 0, 0
$019A	$0863	    			SUBLW	99
$019C	$	L_WordToStr_56:
$019C	$A0D8	    			BTFSS	STATUS, C, 0
$019E	$2A33	    			INCF	WordToStr_len_L0, 1, 0
$01A0	$	L_WordToStr_5:
$01A0	$5030	    			MOVF	FARG_WordToStr+1, 0, 0
$01A2	$0803	    			SUBLW	3
$01A4	$E102	    			BNZ	L_WordToStr_57
$01A6	$502F	    			MOVF	FARG_WordToStr+0, 0, 0
$01A8	$08E7	    			SUBLW	231
$01AA	$	L_WordToStr_57:
$01AA	$A0D8	    			BTFSS	STATUS, C, 0
$01AC	$2A33	    			INCF	WordToStr_len_L0, 1, 0
$01AE	$	L_WordToStr_6:
$01AE	$5030	    			MOVF	FARG_WordToStr+1, 0, 0
$01B0	$0827	    			SUBLW	39
$01B2	$E102	    			BNZ	L_WordToStr_58
$01B4	$502F	    			MOVF	FARG_WordToStr+0, 0, 0
$01B6	$080F	    			SUBLW	15
$01B8	$	L_WordToStr_58:
$01B8	$A0D8	    			BTFSS	STATUS, C, 0
$01BA	$2A33	    			INCF	WordToStr_len_L0, 1, 0
$01BC	$	L_WordToStr_7:
$01BC	$6AED	    			CLRF	POSTDEC0, 0
$01BE	$	L_WordToStr_8:
$01BE	$5033	    			MOVF	WordToStr_len_L0, 0, 0
$01C0	$0800	    			SUBLW	0
$01C2	$E224	    			BC	L_WordToStr_9
$01C4	$0E0A	    			MOVLW	10
$01C6	$6E04	    			MOVWF	STACK_4, 0
$01C8	$0E00	    			MOVLW	0
$01CA	$6E05	    			MOVWF	STACK_4+1, 0
$01CC	$C02F	F000			MOVFF	FARG_WordToStr+0, STACK_0
$01D0	$C030	F001			MOVFF	FARG_WordToStr+1, STACK_0+1
$01D4	$EC4B	F000			CALL	_div_16x16_u
$01D8	$C008	F000			MOVFF	STACK_8, STACK_0
$01DC	$C009	F001			MOVFF	STACK_9, STACK_1
$01E0	$C000	FFEF			MOVFF	STACK_0, INDF0
$01E4	$50EF	    			MOVF	INDF0, 0, 0
$01E6	$5C2F	    			SUBWF	FARG_WordToStr+0, 0, 0
$01E8	$6E00	    			MOVWF	STACK_0, 0
$01EA	$0E00	    			MOVLW	0
$01EC	$5830	    			SUBWFB	FARG_WordToStr+1, 0, 0
$01EE	$6E01	    			MOVWF	STACK_0+1, 0
$01F0	$0E0A	    			MOVLW	10
$01F2	$6E04	    			MOVWF	STACK_4, 0
$01F4	$0E00	    			MOVLW	0
$01F6	$6E05	    			MOVWF	STACK_4+1, 0
$01F8	$EC4B	F000			CALL	_div_16x16_u
$01FC	$C000	F02F			MOVFF	STACK_0, FARG_WordToStr+0
$0200	$C001	F030			MOVFF	STACK_0+1, FARG_WordToStr+1
$0204	$0E30	    			MOVLW	48
$0206	$26ED	    			ADDWF	POSTDEC0, 1, 0
$0208	$0633	    			DECF	WordToStr_len_L0, 1, 0
$020A	$D7D9	    			BRA	L_WordToStr_8
$020C	$	L_WordToStr_9:
$020C	$0012	    			RETURN
$020E	$	_Eeprom_Write:
$020E	$9CA6	    			BCF	EECON1, 6, 0
$0210	$	L_Eeprom_Write_0:
$0210	$A2A6	    			BTFSS	EECON1, 1, 0
$0212	$D002	    			BRA	L_Eeprom_Write_1
$0214	$0000	    			NOP
$0216	$D7FC	    			BRA	L_Eeprom_Write_0
$0218	$	L_Eeprom_Write_1:
$0218	$C02F	FFA9			MOVFF	FARG_Eeprom_Write+0, EEADR
$021C	$C030	FFA8			MOVFF	FARG_Eeprom_Write+1, EEDATA
$0220	$9EA6	    			BCF	EECON1, 7, 0
$0222	$84A6	    			BSF	EECON1, 2, 0
$0224	$9EF2	    			BCF	INTCON, 7, 0
$0226	$0E55	    			MOVLW	85
$0228	$6EA7	    			MOVWF	EECON2, 0
$022A	$0EAA	    			MOVLW	170
$022C	$6EA7	    			MOVWF	EECON2, 0
$022E	$82A6	    			BSF	EECON1, 1, 0
$0230	$8EF2	    			BSF	INTCON, 7, 0
$0232	$94A6	    			BCF	EECON1, 2, 0
$0234	$0012	    			RETURN
$0236	$	_Eeprom_Read:
$0236	$9CA6	    			BCF	EECON1, 6, 0
$0238	$C02F	FFA9			MOVFF	FARG_Eeprom_Read+0, EEADR
$023C	$9EA6	    			BCF	EECON1, 7, 0
$023E	$80A6	    			BSF	EECON1, 0, 0
$0240	$CFA8	F000			MOVFF	EEDATA, STACK_0
$0244	$0012	    			RETURN
$0246	$	_Lcd8_Init:
$0246	$EC07	F000			CALL	_Delay_5500us
$024A	$EC07	F000			CALL	_Delay_5500us
$024E	$EC07	F000			CALL	_Delay_5500us
$0252	$C031	F015			MOVFF	FARG_Lcd8_Init+2, Lcd8bit_main_global_dataAddress
$0256	$C032	F016			MOVFF	FARG_Lcd8_Init+3, Lcd8bit_main_global_dataAddress+1
$025A	$C02F	F017			MOVFF	FARG_Lcd8_Init+0, Lcd8bit_main_global_ctrlAddress
$025E	$C030	F018			MOVFF	FARG_Lcd8_Init+1, Lcd8bit_main_global_ctrlAddress+1
$0262	$C02F	FFE9			MOVFF	FARG_Lcd8_Init+0, FSR0L
$0266	$C030	FFEA			MOVFF	FARG_Lcd8_Init+1, FSR0H
$026A	$90EF	    			BCF	INDF0, __LCD8_RW, 0
$026C	$C031	FFE1			MOVFF	FARG_Lcd8_Init+2, FSR1L
$0270	$C032	FFE2			MOVFF	FARG_Lcd8_Init+3, FSR1H
$0274	$6AE6	    			CLRF	POSTINC1, 0
$0276	$0E11	    			MOVLW	17
$0278	$24E1	    			ADDWF	FSR1L, 0, 0
$027A	$6E00	    			MOVWF	STACK_0, 0
$027C	$C000	FFE1			MOVFF	STACK_0, FSR1L
$0280	$6AE7	    			CLRF	INDF1, 0
$0282	$0E12	    			MOVLW	18
$0284	$5C00	    			SUBWF	STACK_0, 0, 0
$0286	$6EE1	    			MOVWF	FSR1L, 0
$0288	$0E12	    			MOVLW	18
$028A	$26E9	    			ADDWF	FSR0L, 1, 0
$028C	$92EF	    			BCF	INDF0, __LCD8_ENABLE, 0
$028E	$94EF	    			BCF	INDF0, __LCD8_RS, 0
$0290	$90EF	    			BCF	INDF0, __LCD8_RW, 0
$0292	$0E12	    			MOVLW	18
$0294	$5EE9	    			SUBWF	FSR0L, 1, 0
$0296	$94EF	    			BCF	INDF0, __LCD8_RS, 0
$0298	$92EF	    			BCF	INDF0, __LCD8_ENABLE, 0
$029A	$90EF	    			BCF	INDF0, __LCD8_RW, 0
$029C	$0E30	    			MOVLW	48
$029E	$6E34	    			MOVWF	FARG_Lcd8_Cmd+0, 0
$02A0	$EC1C	F000			CALL	_Lcd8_Cmd
$02A4	$0E30	    			MOVLW	48
$02A6	$6E34	    			MOVWF	FARG_Lcd8_Cmd+0, 0
$02A8	$EC1C	F000			CALL	_Lcd8_Cmd
$02AC	$0E30	    			MOVLW	48
$02AE	$6E34	    			MOVWF	FARG_Lcd8_Cmd+0, 0
$02B0	$EC1C	F000			CALL	_Lcd8_Cmd
$02B4	$0E38	    			MOVLW	56
$02B6	$6E34	    			MOVWF	FARG_Lcd8_Cmd+0, 0
$02B8	$EC1C	F000			CALL	_Lcd8_Cmd
$02BC	$0E08	    			MOVLW	8
$02BE	$6E34	    			MOVWF	FARG_Lcd8_Cmd+0, 0
$02C0	$EC1C	F000			CALL	_Lcd8_Cmd
$02C4	$0E01	    			MOVLW	1
$02C6	$6E34	    			MOVWF	FARG_Lcd8_Cmd+0, 0
$02C8	$EC1C	F000			CALL	_Lcd8_Cmd
$02CC	$0E06	    			MOVLW	6
$02CE	$6E34	    			MOVWF	FARG_Lcd8_Cmd+0, 0
$02D0	$EC1C	F000			CALL	_Lcd8_Cmd
$02D4	$0E0C	    			MOVLW	12
$02D6	$6E34	    			MOVWF	FARG_Lcd8_Cmd+0, 0
$02D8	$EC1C	F000			CALL	_Lcd8_Cmd
$02DC	$0E01	    			MOVLW	1
$02DE	$6E19	    			MOVWF	Lcd8bit_main_global_cmd, 0
$02E0	$0012	    			RETURN
$02E2	$	_main:
$02E2	$0E59	    			MOVLW	89
$02E4	$6E1A	    			MOVWF	lstr1_eepron+0, 0
$02E6	$0E20	    			MOVLW	32
$02E8	$6E1B	    			MOVWF	lstr1_eepron+1, 0
$02EA	$0E3D	    			MOVLW	61
$02EC	$6E1C	    			MOVWF	lstr1_eepron+2, 0
$02EE	$0E20	    			MOVLW	32
$02F0	$6E1D	    			MOVWF	lstr1_eepron+3, 0
$02F2	$0E58	    			MOVLW	88
$02F4	$6E1E	    			MOVWF	lstr1_eepron+4, 0
$02F6	$0E5E	    			MOVLW	94
$02F8	$6E1F	    			MOVWF	lstr1_eepron+5, 0
$02FA	$0E32	    			MOVLW	50
$02FC	$6E20	    			MOVWF	lstr1_eepron+6, 0
$02FE	$6A21	    			CLRF	lstr1_eepron+7, 0
$0300	$0E7C	    			MOVLW	124
$0302	$6E22	    			MOVWF	lstr2_eepron+0, 0
$0304	$6A23	    			CLRF	lstr2_eepron+1, 0
;eepron.c,1 :: 			void main () {
;eepron.c,2 :: 			char i = 0;
$0306	$6A24	    			CLRF	main_i_L0, 0
;eepron.c,4 :: 			trisd = 0;
$0308	$6A95	    			CLRF	TRISD, 0
;eepron.c,5 :: 			trise = 0;
$030A	$6A96	    			CLRF	TRISE, 0
;eepron.c,6 :: 			ADCON1 = 0x06;
$030C	$0E06	    			MOVLW	6
$030E	$6EC1	    			MOVWF	ADCON1, 0
;eepron.c,7 :: 			trisb.rb0 = 1;
$0310	$8093	    			BSF	TRISB, 0, 0
;eepron.c,8 :: 			trisb.rb1 = 1;
$0312	$8293	    			BSF	TRISB, 1, 0
;eepron.c,9 :: 			lcd8_config(&porte,&portd,2,1,0,7,6,5,4,3,2,1,0);
$0314	$0E84	    			MOVLW	PORTE
$0316	$6E2F	    			MOVWF	FARG_Lcd8_Init+0, 0
$0318	$0E0F	    			MOVLW	@PORTE
$031A	$6E30	    			MOVWF	FARG_Lcd8_Init+1, 0
$031C	$0E83	    			MOVLW	PORTD
$031E	$6E31	    			MOVWF	FARG_Lcd8_Init+2, 0
$0320	$0E0F	    			MOVLW	@PORTD
$0322	$6E32	    			MOVWF	FARG_Lcd8_Init+3, 0
$0324	$EC23	F001			CALL	_Lcd8_Init
;eepron.c,10 :: 			lcd8_cmd(lcd_clear);
$0328	$0E01	    			MOVLW	1
$032A	$6E34	    			MOVWF	FARG_Lcd8_Cmd+0, 0
$032C	$EC1C	F000			CALL	_Lcd8_Cmd
;eepron.c,11 :: 			lcd8_cmd(lcd_cursor_off);
$0330	$0E0C	    			MOVLW	12
$0332	$6E34	    			MOVWF	FARG_Lcd8_Cmd+0, 0
$0334	$EC1C	F000			CALL	_Lcd8_Cmd
;eepron.c,12 :: 			lcd8_out(1, 1, "Y = X^2");
$0338	$0E01	    			MOVLW	1
$033A	$6E2F	    			MOVWF	FARG_LCD8_Out+0, 0
$033C	$0E01	    			MOVLW	1
$033E	$6E30	    			MOVWF	FARG_LCD8_Out+1, 0
$0340	$0E1A	    			MOVLW	lstr1_eepron
$0342	$6E31	    			MOVWF	FARG_LCD8_Out+2, 0
$0344	$0E00	    			MOVLW	@lstr1_eepron
$0346	$6E32	    			MOVWF	FARG_LCD8_Out+3, 0
$0348	$EC69	F000			CALL	_LCD8_Out
;eepron.c,13 :: 			while (1) {
$034C	$	L_main_0:
;eepron.c,14 :: 			for(i = 1 ; i < 8 ; i++) {
$034C	$0E01	    			MOVLW	1
$034E	$6E24	    			MOVWF	main_i_L0, 0
$0350	$	L_main_2:
$0350	$0E08	    			MOVLW	8
$0352	$5C24	    			SUBWF	main_i_L0, 0, 0
$0354	$E226	    			BC	L_main_3
;eepron.c,15 :: 			wordToStr(i, c);
$0356	$C024	F02F			MOVFF	main_i_L0, FARG_WordToStr+0
$035A	$0E00	    			MOVLW	0
$035C	$6E30	    			MOVWF	FARG_WordToStr+1, 0
$035E	$0E25	    			MOVLW	main_c_L0
$0360	$6E31	    			MOVWF	FARG_WordToStr+2, 0
$0362	$0E00	    			MOVLW	@main_c_L0
$0364	$6E32	    			MOVWF	FARG_WordToStr+3, 0
$0366	$ECAD	F000			CALL	_WordToStr
;eepron.c,16 :: 			eeprom_write(0x20 + i, c);
$036A	$5024	    			MOVF	main_i_L0, 0, 0
$036C	$0F20	    			ADDLW	32
$036E	$6E2F	    			MOVWF	FARG_Eeprom_Write+0, 0
$0370	$0E25	    			MOVLW	main_c_L0
$0372	$6E30	    			MOVWF	FARG_Eeprom_Write+1, 0
$0374	$EC07	F001			CALL	_Eeprom_Write
;eepron.c,17 :: 			wordToStr(i * i, c);
$0378	$5024	    			MOVF	main_i_L0, 0, 0
$037A	$0224	    			MULWF	main_i_L0, 0
$037C	$CFF3	F02F			MOVFF	PRODL, FARG_WordToStr+0
$0380	$CFF4	F030			MOVFF	PRODH, FARG_WordToStr+1
$0384	$0E25	    			MOVLW	main_c_L0
$0386	$6E31	    			MOVWF	FARG_WordToStr+2, 0
$0388	$0E00	    			MOVLW	@main_c_L0
$038A	$6E32	    			MOVWF	FARG_WordToStr+3, 0
$038C	$ECAD	F000			CALL	_WordToStr
;eepron.c,18 :: 			eeprom_write(0x50 + i, c);
$0390	$5024	    			MOVF	main_i_L0, 0, 0
$0392	$0F50	    			ADDLW	80
$0394	$6E2F	    			MOVWF	FARG_Eeprom_Write+0, 0
$0396	$0E25	    			MOVLW	main_c_L0
$0398	$6E30	    			MOVWF	FARG_Eeprom_Write+1, 0
$039A	$EC07	F001			CALL	_Eeprom_Write
;eepron.c,19 :: 			}
$039E	$	L_main_4:
;eepron.c,14 :: 			for(i = 1 ; i < 8 ; i++) {
$039E	$2A24	    			INCF	main_i_L0, 1, 0
;eepron.c,19 :: 			}
$03A0	$D7D7	    			BRA	L_main_2
$03A2	$	L_main_3:
;eepron.c,20 :: 			for(i = 1 ; i < 8 ; i++) {
$03A2	$0E01	    			MOVLW	1
$03A4	$6E24	    			MOVWF	main_i_L0, 0
$03A6	$	L_main_5:
$03A6	$0E08	    			MOVLW	8
$03A8	$5C24	    			SUBWF	main_i_L0, 0, 0
$03AA	$E249	    			BC	L_main_6
;eepron.c,21 :: 			lcd8_out(2, 0, eeprom_read(0x20 + i));
$03AC	$5024	    			MOVF	main_i_L0, 0, 0
$03AE	$0F20	    			ADDLW	32
$03B0	$6E2F	    			MOVWF	FARG_Eeprom_Read+0, 0
$03B2	$EC1B	F001			CALL	_Eeprom_Read
$03B6	$C000	F031			MOVFF	STACK_0, FARG_LCD8_Out+2
$03BA	$0E00	    			MOVLW	0
$03BC	$6E32	    			MOVWF	FARG_LCD8_Out+3, 0
$03BE	$0E02	    			MOVLW	2
$03C0	$6E2F	    			MOVWF	FARG_LCD8_Out+0, 0
$03C2	$6A30	    			CLRF	FARG_LCD8_Out+1, 0
$03C4	$EC69	F000			CALL	_LCD8_Out
;eepron.c,22 :: 			lcd8_out(2, 6, "|");
$03C8	$0E02	    			MOVLW	2
$03CA	$6E2F	    			MOVWF	FARG_LCD8_Out+0, 0
$03CC	$0E06	    			MOVLW	6
$03CE	$6E30	    			MOVWF	FARG_LCD8_Out+1, 0
$03D0	$0E22	    			MOVLW	lstr2_eepron
$03D2	$6E31	    			MOVWF	FARG_LCD8_Out+2, 0
$03D4	$0E00	    			MOVLW	@lstr2_eepron
$03D6	$6E32	    			MOVWF	FARG_LCD8_Out+3, 0
$03D8	$EC69	F000			CALL	_LCD8_Out
;eepron.c,23 :: 			lcd8_out(2, 7, eeprom_read(0x50 + i));
$03DC	$5024	    			MOVF	main_i_L0, 0, 0
$03DE	$0F50	    			ADDLW	80
$03E0	$6E2F	    			MOVWF	FARG_Eeprom_Read+0, 0
$03E2	$EC1B	F001			CALL	_Eeprom_Read
$03E6	$C000	F031			MOVFF	STACK_0, FARG_LCD8_Out+2
$03EA	$0E00	    			MOVLW	0
$03EC	$6E32	    			MOVWF	FARG_LCD8_Out+3, 0
$03EE	$0E02	    			MOVLW	2
$03F0	$6E2F	    			MOVWF	FARG_LCD8_Out+0, 0
$03F2	$0E07	    			MOVLW	7
$03F4	$6E30	    			MOVWF	FARG_LCD8_Out+1, 0
$03F6	$EC69	F000			CALL	_LCD8_Out
;eepron.c,24 :: 			delay_ms(1000);
$03FA	$0E0B	    			MOVLW	11
$03FC	$6E0C	    			MOVWF	STACK_12, 0
$03FE	$0EFF	    			MOVLW	255
$0400	$6E0B	    			MOVWF	STACK_11, 0
$0402	$0EFF	    			MOVLW	255
$0404	$6E0A	    			MOVWF	STACK_10, 0
$0406	$2E0C	    			DECFSZ	STACK_12, F, 0
$0408	$D001	    			BRA	$+2
$040A	$D007	    			BRA	$+8
$040C	$2E0B	    			DECFSZ	STACK_11, F, 0
$040E	$D001	    			BRA	$+2
$0410	$D003	    			BRA	$+4
$0412	$2E0A	    			DECFSZ	STACK_10, F, 0
$0414	$D7FE	    			BRA	$-1
$0416	$D7FA	    			BRA	$-5
$0418	$D7F6	    			BRA	$-9
$041A	$0E33	    			MOVLW	51
$041C	$6E0B	    			MOVWF	STACK_11, 0
$041E	$0EFF	    			MOVLW	255
$0420	$6E0A	    			MOVWF	STACK_10, 0
$0422	$2E0B	    			DECFSZ	STACK_11, F, 0
$0424	$D001	    			BRA	$+2
$0426	$D003	    			BRA	$+4
$0428	$2E0A	    			DECFSZ	STACK_10, F, 0
$042A	$D7FE	    			BRA	$-1
$042C	$D7FA	    			BRA	$-5
$042E	$0E88	    			MOVLW	136
$0430	$6E0A	    			MOVWF	STACK_10, 0
$0432	$2E0A	    			DECFSZ	STACK_10, F, 0
$0434	$D7FE	    			BRA	$-1
$0436	$0000	    			NOP
$0438	$0000	    			NOP
;eepron.c,25 :: 			}
$043A	$	L_main_7:
;eepron.c,20 :: 			for(i = 1 ; i < 8 ; i++) {
$043A	$2A24	    			INCF	main_i_L0, 1, 0
;eepron.c,25 :: 			}
$043C	$D7B4	    			BRA	L_main_5
$043E	$	L_main_6:
;eepron.c,32 :: 			}
$043E	$D786	    			BRA	L_main_0
;eepron.c,33 :: 			}
$0440	$D7FF	    			BRA	$
