;  ASM code generated by mikroVirtualMachine for PIC - V. 7.0.0.3
;  Date/Time: 14/06/2017 09:27:18
;  Info: http://www.mikroelektronika.co.yu


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$EF04	F000			GOTO	_main
$0008	$	_main:
;Contador.c,2 :: 			void main() {
;Contador.c,3 :: 			int a = 0;
$0008	$6A15	    			CLRF	main_a_L0, 0
$000A	$6A16	    			CLRF	main_a_L0+1, 0
;Contador.c,4 :: 			t0con = 0b11000111;
$000C	$0EC7	    			MOVLW	199
$000E	$6ED5	    			MOVWF	T0CON, 0
;Contador.c,5 :: 			tmr0l = 0b00000000;
$0010	$6AD6	    			CLRF	TMR0L, 0
;Contador.c,6 :: 			trisd = 0;
$0012	$6A95	    			CLRF	TRISD, 0
;Contador.c,7 :: 			portd = 0xff;
$0014	$0EFF	    			MOVLW	255
$0016	$6E83	    			MOVWF	PORTD, 0
;Contador.c,8 :: 			while (1) {
$0018	$	L_main_0:
;Contador.c,9 :: 			if (tmr0l == 0b11111111) {
$0018	$50D6	    			MOVF	TMR0L, 0, 0
$001A	$0AFF	    			XORLW	255
$001C	$E114	    			BNZ	L_main_2
;Contador.c,10 :: 			a += 1;
$001E	$0E01	    			MOVLW	1
$0020	$2415	    			ADDWF	main_a_L0, 0, 0
$0022	$6E01	    			MOVWF	STACK_1, 0
$0024	$0E00	    			MOVLW	0
$0026	$2016	    			ADDWFC	main_a_L0+1, 0, 0
$0028	$6E02	    			MOVWF	STACK_1+1, 0
$002A	$C001	F015			MOVFF	STACK_1, main_a_L0
$002E	$C002	F016			MOVFF	STACK_1+1, main_a_L0+1
;Contador.c,11 :: 			tmr0l = 0b00000000;
$0032	$6AD6	    			CLRF	TMR0L, 0
;Contador.c,12 :: 			if (a == MULTI * 10 ) {
$0034	$5002	    			MOVF	STACK_1+1, 0, 0
$0036	$0A01	    			XORLW	1
$0038	$E102	    			BNZ	L_main_4
$003A	$0E36	    			MOVLW	54
$003C	$1801	    			XORWF	STACK_1, 0, 0
$003E	$	L_main_4:
$003E	$E103	    			BNZ	L_main_3
;Contador.c,13 :: 			portd = ~portd;
$0040	$1E83	    			COMF	PORTD, 1, 0
;Contador.c,14 :: 			a = 0;
$0042	$6A15	    			CLRF	main_a_L0, 0
$0044	$6A16	    			CLRF	main_a_L0+1, 0
;Contador.c,15 :: 			}
$0046	$	L_main_3:
;Contador.c,16 :: 			}
$0046	$	L_main_2:
;Contador.c,17 :: 			}
$0046	$D7E8	    			BRA	L_main_0
;Contador.c,18 :: 			}
$0048	$D7FF	    			BRA	$
